src/Entity/Commnt.php
<?php

namespace App\Entity;

use App\Repository\CommntRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommntRepository::class)]
class Commnt
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $user = null;

    #[ORM\Column(length: 255)]
    private ?string $text = null;

    #[ORM\Column]
    private ?int $lik = null;

    #[ORM\Column]
    private ?int $post_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?string
    {
        return $this->user;
    }

    public function setUser(string $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getLik(): ?int
    {
        return $this->lik;
    }

    public function setLik(int $lik): self
    {
        $this->lik = $lik;

        return $this;
    }

    public function getPostId(): ?int
    {
        return $this->post_id;
    }

    public function setPostId(int $post_id): self
    {
        $this->post_id = $post_id;

        return $this;
    }
}

src/Entity/Lecon.php
<?php

namespace App\Entity;

use App\Repository\LeconRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LeconRepository::class)]
class Lecon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $id_ch = null;

    #[ORM\Column(length: 255)]
    private ?string $video = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $descr = null;

    #[ORM\Column]
    private ?bool $lu = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdCh(): ?int
    {
        return $this->id_ch;
    }

    public function setIdCh(int $id_ch): self
    {
        $this->id_ch = $id_ch;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getDescr(): ?string
    {
        return $this->descr;
    }

    public function setDescr(string $descr): self
    {
        $this->descr = $descr;

        return $this;
    }

    public function isLu(): ?bool
    {
        return $this->lu;
    }

    public function setLu(bool $lu): self
    {
        $this->lu = $lu;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Type;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use App\Entity\ClubsClubList;

use App\Entity\ClubsEvenements;
use App\Repository\ClubsClubListRepository;
use App\Repository\ClubsEvenementsRepository;
use App\Repository\CoursRepository;
use App\Repository\CourstdRepository;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;



use Symfony\Component\Form\FormBuilderInterface;


class MainController extends AbstractController
{
    #[Route('/main', name: 'app_main')]
    public function index(): Response
    {
        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }

    #[Route('/', name: 'home')]
    public function home(CoursRepository $cr,ManagerRegistry $doctrine,CourstdRepository $courstdRepository)
    {
        $matiere = $courstdRepository->findBy([],[],4);
        $events = $doctrine->getRepository(ClubsEvenements::class)->findBy([],['id'=>'DESC'],2);
        $cours=$cr->findBy([],['nom'=> 'DESC'],3);
        return $this-> render('main/home.html.twig',['c'=>$cours,'eventhome'=>$events,  'matieres' => $matiere,]);
    }
    // #[Route('/login', name: 'login')]
    // public function login()
    // {
    //     return $this-> render('main/compte.html.twig');
    // }

    #[Route('/test', name: 'test')]
    public function test()
    {
        return $this-> render('main/test.html.twig');
    }
    #[Route('/clubs', name: 'c_home')]
    public function clubs_home(ManagerRegistry $doctrine):Response    {
        $events = $doctrine->getRepository(ClubsEvenements::class)->findBy([],['id'=>'DESC'],4);

        return $this-> render('main/clubs_h.html.twig',['eventhome'=>$events]);
    }
    #[Route('/m', name: 'cc_home')]
    public function m()
    {
        return $this-> render('main/main.html.twig');
    }
    #[Route('/tesst', name: 'cc_home')]
    public function tesst()
    {
        return $this-> render('main/test.html.twig');
    }
    // #[Route('/clubs/list/home', name: 'clubs_list_home')]
    // public function clubs_list_home()
    // {
    //     return $this-> render('main/liste_clubs.html.twig');
    // }
    #[Route('/clubs/list', name: 'clubs_list')]
    public function rep(ManagerRegistry $doctrine):Response
    {
       $clubs = $doctrine->getRepository(ClubsClublist::class)->findAll();

       return $this->render('main/liste_clubs.html.twig',['clubs'=>$clubs]);
    }
    #[Route('/club/{id}',name:"club")]
    public function show($id,ManagerRegistry $doctrine,ClubsClubListRepository $repo):Response
    {   
        // $oneclub=$doctrine->getRepository(ClubsClublist::class)->find($id);
        $oneclub=$repo->find($id);
        return $this->render('main/club_show.html.twig',['oneclub'=>$oneclub]);

    }
    #[Route('/new', name: 'club_create')]
    #[Route('/new/{id}/edit', name: 'club_edit')]

    public function club_manage(ClubsClubList $oneclub=null,Request $request,EntityManagerInterface $entityManager ):Response
    {
        if(!$oneclub)
        {   $oneclub=new ClubsClubList();}
        $form=$this->createFormBuilder($oneclub)
        ->add('ClubNom',TextType::class,[
            'attr'=>['placeholder' =>"Nom du club ",'class'=>'form-control']
        ])
        ->add('ClubMembersNb',TextType::class,[
            'attr'=>['placeholder' =>"Nombre des membres",'class'=>'form-control']
        ])
        ->add("ClubInstitut" ,ChoiceType::class,['choices'=> 
            [ 'Issat Sousse'=> 'Issat Sousse'],
        ])
        ->add('ClubActivityType',ChoiceType::class,['choices'=>[
            'Génie civil'=>'Génie civil',
            'Ingénierie en informatique GL'=>'Ingénierie en informatique GL',
            'Génie Mécanique'=>'Génie Mécanique',   
            'Systémes Embarqués'=>'Systémes Embarqués',
            'Electro-Mécanique'=>'Electro-Mécanique',
            'sciences Informatique'=> 'sciences Informatique',
            'Mécatronique Automobile'=>'Mécatronique Automobile',
            'Mécatronique Industrielle'=>'Mécatronique Industrielle',
            'Cycle préparatoire intégrée'=>'Cycle préparatoire intégrée',
            'Ingénierie en informatique Industrielle'=>'Ingénierie en informatique Industrielle',
        ],
    ])
        
        ->add('ClubRepName',TextType::class,['attr'=>['placeholder' =>"Nom du representant",'class'=>'form-control']])
        ->add('ClubRepEmail',EmailType::class,['attr'=>['placeholder' =>"Email du representant",'class'=>'form-control']])
        ->add('ClubDescription',TextareaType::class,['attr'=>['placeholder' =>"Plus de details",'class'=>'form-control']])
        ->add('ClubImg', FileType::class,[
        'required' => false,
        'mapped' => false,])

        // ->add('Enregistrer', SubmitType::class, ['label' => 'Créer Club'])
        ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
            {if(!$oneclub->getId())
        {
            $oneclub->SetCreatedAt(new \DateTime);
            $oneclub->setNumTab(1);}
            //image upload
            $photoFile = $form->get('ClubImg')->getData();
            $newFilename = uniqid().'.'.$photoFile->guessExtension();
            try {
                // Move the uploaded file to a directory
                $photoFile->move(
                    $this->getParameter('kernel.project_dir').'/public/assets/images',
                    $newFilename,
                    // $newFilename= public/assets/images/+ $newFilename
                   

                );
                $oneclub->setClubImg('assets/images/'.$newFilename);

            }
             catch (FileException $e) {}
           



            $entityManager->persist($oneclub);
            $entityManager->flush();
            return $this->redirectToRoute('club',['id'=>$oneclub->getId()]);
            // $this->addFlash('success', 'Form submitted successfully!');

        }
        dump($oneclub);

        return $this-> render('main/create_club.html.twig',[
            'formClub'=>$form->createView(),
            'editMode'=>$oneclub->getId()!==null
        ]);
    }
    #[Route('/events/list', name: 'events_list')]
    public function repoevent(ManagerRegistry $doctrine):Response
    {
       $events = $doctrine->getRepository(ClubsEvenements::class)->findAll();

       return $this->render('main/liste_evenements.html.twig',['events'=>$events]);
    }
    #[Route('/event/{id}',name:"event")]
    public function showevent($id,ManagerRegistry $doctrine,ClubsEvenementsRepository $repoeve):Response
    {   
        // $oneclub=$doctrine->getRepository(ClubsClublist::class)->find($id);
        $oneevent=$repoeve->find($id);
        return $this->render('main/event_show.html.twig',['oneevent'=>$oneevent]);

    }
    // #[Route('/eventshome', name: 'events_home')]
    // public function homeevent(ManagerRegistry $doctrine):Response
    // {
    //    $events = $doctrine->getRepository(ClubsEvenements::class)->findBy([],['id'=>'DESC'],3);

    //    return $this->render('main/clubs_h.html.twig',['eventhome'=>$events]);
    // }
    #[Route('/newevent', name: 'event_create')]
    #[Route('/newevent/{id}/edit', name: 'event_edit')]

    public function event_manage(ClubsEvenements $oneevent=null,Request $request,EntityManagerInterface $entityManager,ManagerRegistry $doctrine ):Response
    {
        if(!$oneevent)
        {   $oneevent=new ClubsEvenements();}
        $form=$this->createFormBuilder($oneevent)
        ->add('EvenementNom',TextType::class,[
            'attr'=>['placeholder' =>"Nom d'evenemnt ",'class'=>'form-control']
        ])
        ->add('EvenementClubNom',TextType::class,[
            'attr'=>['placeholder' =>"Nom du club organisateur ",'class'=>'form-control']
        ])
        ->add('EvenementType',TextType::class,[
            'attr'=>['placeholder' =>"Type d'événement",'class'=>'form-control']
        ])
        ->add("EvenementDate" ,DateType::class,['attr'=>['placeholder' =>"Date d'événement" ],
        ])
       
        ->add('EvenementLieu',TextType::class,['attr'=>['placeholder' =>"Lieu de l'événement",'class'=>'form-control']])
        ->add('EvenementLien',TextType::class,['attr'=>['placeholder' =>"Lien d'événement",'class'=>'form-control']])
        ->add('EvenementPrix',NumberType::class,['attr'=>['placeholder' =>"frais de participation", ]])
        ->add('EvenementImage', FileType::class,[
        'required' => false,
        'mapped' => false,])

        // ->add('Enregistrer', SubmitType::class, ['label' => 'Créer Club'])
        ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {   if(!$oneevent->getId())
            {  
                $oneevent->SetCreatedAt(new \DateTime);
                $oneevent->setTabNum(2);
                $clubName = $oneevent->getEvenementClubNom();
                $club = $doctrine->getRepository(ClubsClubList::class)->findOneBy(['club_nom' => $clubName]);
                if ($club) {
                    $oneevent->setClbId($club);
                } else {

templates/main/aide.html.twig
{% block stylesheets %}
    <link rel="stylesheet" href={{asset("assets/css/style.css")}}>
    <link rel="stylesheet" href={{asset("assets/css/aide.css")}}>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/450c9bb9e7.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation:wght@600&display=swap" rel="stylesheet">
{% endblock %}
{% block body %}
<body style="background-color: rgb(2, 2, 39); height: 98%; width: 96%;">
    

    
         <div class="asideNav" id="asideNav" onmouseenter="f1()" onmouseleave="f2()">
            
            {% include "aside.html.twig" %}
        </div>
                <div class="main" id="main" style="overflow-y: scroll;">
                    {% include "navii.html.twig" %}
                    
                    <div class="ajtpost">
                        <form action="" method="post" class="frm">
                            <textarea name="text" id="" cols="30" rows="1" placeholder="Ton question..."></textarea>
                            <button type="submit" name="post" value="post" class="btn btn-secondary">Poster</button>
                        </form>
                    </div>
                    {% for p in post %}
                        
                    
                    <div class="comments">
                        <p>
                            <span style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; font-weight: 700;">{{p.user}}</span><br>
                           {{p.text}}
                        </p>
                        <div class="like">
                            <form action="" method="post" style="margin-top: 14px;">
                                <input type="text" name="id" style="display: none;" value="{{p.id}}">
                                <button name="like" value="like" class="btnj" type="submit">j'aime ({{p.lik}})</button>
                            </form>
                            <button class="collapsible btnj">commentaire</button>
                        </div>
                        <div class="content" style="margin-bottom: 10px;">
                            {% for c in comnt %}
                               {% if c.postId==p.id %}
                                
                               
                            <p>
                                <span style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; font-weight: 700;">{{c.user}}</span><br>
                               {{c.text}}
                            </p>
                            <div class="like">
                                <form action="" method="post" style="margin-top: 14px;"><button class="btnj" type="submit">j'aime ({{c.lik}})</button></form>
                            </div>
                            {% endif %}
                            {% endfor %}
                            
                            <form action="" method="post" class="frm" style="margin: 5px auto; width: 90%;">
                                <input type="text" name="id" style="display: none;" value="{{p.id}}">
                                <textarea name="text" id="" cols="30" rows="1" placeholder="Commentaire..."></textarea>
                                <button type="submit" name="commnt" value="commnt" class="btn btn-secondary">Poster</button>
                            </form>
                             
                            
                           
                        </div>
                    </div>
                    {% endfor %}
                    
                     
                </div>

        </body>
{% endblock %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
         
        const main=document.getElementById("main");
        const nav=document.getElementById("nav");
        const asideNav_span1=document.getElementById("asideNav_span1");
        const asideNav_span2=document.getElementById("asideNav_span2");
        const asideNav_span3=document.getElementById("asideNav_span3");
        const asideNav_span4=document.getElementById("asideNav_span4");

       function f1(){
        console.log('hi');
        main.classList.add("active");
        nav.classList.add('ac')
        asideNav.classList.add('ac')
        asideNav_span1.style.color="white"
        asideNav_span2.style.color="white"
        asideNav_span3.style.color="white"
        asideNav_span4.style.color="white"

        
       }
       function f2(){
        console.log('bye');
        main.classList.remove("active");
        nav.classList.remove('ac')

       }
       var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var content = this.parentElement.nextElementSibling;
            console.log(content)
            if (content.style.display === "block") {
                content.style.display = "none";
              } else {
                content.style.display = "block";
              }
        });
    }
    </script>
{% endblock %}

templates/main/club_show.html.twig
{% block stylesheets %}
<link rel="stylesheet" href="{{asset('assets/css/c_show.css')}}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />


{% endblock %}
{% block body %}
<nav id="navbarclubs">
    <div>
       <ul>
       <li><a href="/clubs">Accueil</a></li>
       <li>
        <div class="dropdown">
            <button class="dropbtn" style="font-weight: 600;">Clubs</button>
            <div class="dropdown-content">
                <a href="/new/">créer club</a>
              <a href="/clubs/list">Nos clubs</a>
            
            </div>
          </div>
       </li>
       <li>
        <div class="dropdown">
            <button class="dropbtn" style="font-weight: 600;">Evenements</button>
            <div class="dropdown-content">
                <a href="/newevent/">créer Evenement</a>
              <a href="/events/list">Nos Evenement</a>
            
            </div>
          </div>
       </li>
       <li>Aide</li>
       
      </ul>
   </div>
     <div id="sign-up">
       <button id="sign" class="bts-logs"><a class ="f" href="formc.html">Sign up</a></button>
       <button id="log" class="bts-logs"><a  class ="f" href="login.html">log in</a></button>
     </div>
</nav>

<article>
    <img id="img" src="{{asset(oneclub.ClubImg)}}"/>
    <section class="details_club" style=" height: 500px;">
        <h1>{{oneclub.ClubNom}}</h1></br>
        <a id="modifier" href="{{path('club_edit',{'id':oneclub.id})}}"><span class="material-symbols-outlined">
            edit</span></a>
        <span id="number"><span style="color:white">Nombre des membres:</span>&nbsp; {{oneclub.ClubMembersNb}}</span></br>
        <span id="institut"><span style="color:white">Institut:</span>&nbsp; {{oneclub.ClubInstitut}}</span></br>
        <span id="activity"><span style="color:white">Type d'activité:</span>&nbsp; {{oneclub.ClubActivityType}}</span></br>
        <span id="crname"><span style="color:white">Le nom du representant:</span>&nbsp; {{oneclub.ClubRepName}}</span></br>
        <span id="cremail"><span style="color:white">l'email du représentant:</span>&nbsp; {{oneclub.ClubRepEmail}}</span></br>
        <div id="cdescription" ><span style="color:white">Description :</span>&nbsp; {{oneclub.ClubDescription}}</div></br>
        <button id="f-button">Follow</button>
        
    </section>
</article>
{% endblock %}

templates/main/lecon.html.twig
{% block stylesheets %}
    <link rel="stylesheet" href={{asset("assets/css/style.css")}}>
    <link rel="stylesheet" href={{asset("assets/css/lec.css")}}>
    
    <link rel="stylesheet" href={{asset("assets/css/collaps.css")}}>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/450c9bb9e7.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation:wght@600&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
{% endblock %}
{% block body %}
<body style="background-color: rgb(2, 2, 39); height: 98%; width: 96%;">
    

    
         <div class="asideNav" id="asideNav" onmouseenter="f1()" onmouseleave="f2()">
            
            {% include "aside.html.twig" %}
        </div>
        <div class="main" id="main" style="margin-top:-2px ; padding-top: 8px; overflow-y: scroll;">
                {% include "navii.html.twig" %}
                
                {% for row in cours %}
                <div class="titre">
                    {{row.nom}}
                    <div class="progress" >
                        <div class="progress-bar progress-bar-striped " style="background-color: cadetblue;" id="prog" role="progressbar"  aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">{{row.progres}}%</div>
                </div>
                <script>
                    const prog=document.getElementById('prog').style.width='{{row.progres}}%';
                </script>
                </div>
            <div class="ntt">
                <div class="collaps" style="height: fit-content;">
                    {% for ch in c  %}   
                        <button type="button" class="collapsible" style="font-size:1.3rem;
                                font-weight:650;">{{ch.nom}}</button>
                        <div class="content" >
                            {% for lec in l %}
                                {% if lec.idCh == ch.id %}
                                    <p> 
                                        <a class="mmm" style="font-size: 1.2rem;" href="{{path('lecon',{'id':row.id,'idLec':lec.id})}}">
                                            - {{ lec.nom}} 
                                        </a> 
                                        <i id="{{lec.id}}" style="font-size: 15px;" class="fa-solid fa-check"></i>
                                    </p>
                                    
                                    {% if lec.lu==1 %}
                                    
                                    <script>
                                        
                                        document.getElementById('{{lec.id}}').style.color="green";
                                    </script>
                        
                    {% endif %}    
                                {% endif %} 
                                
                            {% endfor %}                      
                        </div> 
                    {% endfor %}
                </div>
                
                <div class="courr"  style="background-color: rgb(245, 245, 211);">
                    
                    {% for det in detL %}
                    <div class="read" style="background-color: rgba(253, 240, 217, 0.363);">
                        <h5 style="font-weight: 600; font-size: 18px;margin-left: 20px;">{{ det.nom}}</h5>
                        <div class="lu">
                            <form action="" method="post" id="btnr"> <button type="submit" value="read" name="read" style="border: 1px solide green; margin-right: 50px;" onclick="read()" class="btn btn-outline-success ">Marquer comme lu</button></form>
                            <div  id="check" class="disp"><i style="color: green; font-size: 3.5rem; margin-right: 70px;"class="fa-solid fa-circle-check "></i></div>
                        </div>
                    </div>
                   
                    
                    <div class="contnt">
                        
                        <div class="vid" style=" display: flex; justify-content: center; width: 90%; margin: 0 auto;" >
                            <video style="width: 100%; height: 450px;"  controls src="assets/video/{{det.video}}" type="video/mp4"></video>
                        </div>
                        <div class="desc" >
                            
                            {{det.descr}}
                        </div>
                    </div>
                    {% if det.lu==1 %}
                    <script>
                        const check=document.getElementById('check');
                        const btnr=document.getElementById('btnr');
                        check.classList.remove('disp');
                        btnr.classList.add('disp');
                    </script>
                        
                    {% endif %}
                    {% endfor %}
                    
                    
                </div>
                        
            </div>
            {% endfor %}
        </body>
        
{% endblock %}

<script>
   
    const main=document.getElementById("main");
        const nav=document.getElementById("nav");
        const asideNav_span1=document.getElementById("asideNav_span1");
        const asideNav_span2=document.getElementById("asideNav_span2");
        const asideNav_span3=document.getElementById("asideNav_span3");
        const asideNav_span4=document.getElementById("asideNav_span4");

       function f1(){
        console.log('hi');
        main.classList.add("active");
        nav.classList.add('ac')
        asideNav.classList.add('ac')
        asideNav_span1.style.color="white"
        asideNav_span2.style.color="white"
        asideNav_span3.style.color="white"
        asideNav_span4.style.color="white"

        
       }
       function f2(){
        console.log('bye');
        main.classList.remove("active");
        nav.classList.remove('ac')

       }
   
   function read(){
        check.classList.remove('disp');
        btnr.classList.add('disp');
   }
   var coll = document.getElementsByClassName("collapsible");
   var i;
                 
   for  ( i = 0; i < coll.length; i++) {
     coll[i].addEventListener("click", function() {
       this.classList.toggle("active");
       var content = this.nextElementSibling;
       if (content.style.maxHeight){
         content.style.maxHeight = null;
       } else {
         content.style.maxHeight = content.scrollHeight + "px";
       }
     });
   }
</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"></script>